// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of ap_return
//        bit 0  - ap_return[0] (Read)
//        others - reserved
// 0x18 : Data signal of sourceAddress
//        bit 31~0 - sourceAddress[31:0] (Read/Write)
// 0x1c : Control signal of sourceAddress
//        bit 0  - sourceAddress_ap_vld (Read/Write/SC)
//        others - reserved
// 0x20 : Data signal of key_in_V
//        bit 31~0 - key_in_V[31:0] (Read/Write)
// 0x24 : Data signal of key_in_V
//        bit 31~0 - key_in_V[63:32] (Read/Write)
// 0x28 : Data signal of key_in_V
//        bit 31~0 - key_in_V[95:64] (Read/Write)
// 0x2c : Data signal of key_in_V
//        bit 31~0 - key_in_V[127:96] (Read/Write)
// 0x30 : Control signal of key_in_V
//        bit 0  - key_in_V_ap_vld (Read/Write/SC)
//        others - reserved
// 0x34 : Data signal of iv_V
//        bit 31~0 - iv_V[31:0] (Read/Write)
// 0x38 : Data signal of iv_V
//        bit 31~0 - iv_V[63:32] (Read/Write)
// 0x3c : Data signal of iv_V
//        bit 31~0 - iv_V[95:64] (Read/Write)
// 0x40 : Data signal of iv_V
//        bit 31~0 - iv_V[127:96] (Read/Write)
// 0x44 : Control signal of iv_V
//        bit 0  - iv_V_ap_vld (Read/Write/SC)
//        others - reserved
// 0x48 : Data signal of destinationAddress
//        bit 31~0 - destinationAddress[31:0] (Read/Write)
// 0x4c : Control signal of destinationAddress
//        bit 0  - destinationAddress_ap_vld (Read/Write/SC)
//        others - reserved
// 0x50 : Data signal of numBytes
//        bit 31~0 - numBytes[31:0] (Read/Write)
// 0x54 : Control signal of numBytes
//        bit 0  - numBytes_ap_vld (Read/Write/SC)
//        others - reserved
// 0x58 : Data signal of mode
//        bit 31~0 - mode[31:0] (Read/Write)
// 0x5c : Control signal of mode
//        bit 0  - mode_ap_vld (Read/Write/SC)
//        others - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XAES_AXILITES_ADDR_AP_CTRL                 0x00
#define XAES_AXILITES_ADDR_GIE                     0x04
#define XAES_AXILITES_ADDR_IER                     0x08
#define XAES_AXILITES_ADDR_ISR                     0x0c
#define XAES_AXILITES_ADDR_AP_RETURN               0x10
#define XAES_AXILITES_BITS_AP_RETURN               1
#define XAES_AXILITES_ADDR_SOURCEADDRESS_DATA      0x18
#define XAES_AXILITES_BITS_SOURCEADDRESS_DATA      32
#define XAES_AXILITES_ADDR_SOURCEADDRESS_CTRL      0x1c
#define XAES_AXILITES_ADDR_KEY_IN_V_DATA           0x20
#define XAES_AXILITES_BITS_KEY_IN_V_DATA           128
#define XAES_AXILITES_ADDR_KEY_IN_V_CTRL           0x30
#define XAES_AXILITES_ADDR_IV_V_DATA               0x34
#define XAES_AXILITES_BITS_IV_V_DATA               128
#define XAES_AXILITES_ADDR_IV_V_CTRL               0x44
#define XAES_AXILITES_ADDR_DESTINATIONADDRESS_DATA 0x48
#define XAES_AXILITES_BITS_DESTINATIONADDRESS_DATA 32
#define XAES_AXILITES_ADDR_DESTINATIONADDRESS_CTRL 0x4c
#define XAES_AXILITES_ADDR_NUMBYTES_DATA           0x50
#define XAES_AXILITES_BITS_NUMBYTES_DATA           32
#define XAES_AXILITES_ADDR_NUMBYTES_CTRL           0x54
#define XAES_AXILITES_ADDR_MODE_DATA               0x58
#define XAES_AXILITES_BITS_MODE_DATA               32
#define XAES_AXILITES_ADDR_MODE_CTRL               0x5c

