// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xaes.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XAes_CfgInitialize(XAes *InstancePtr, XAes_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XAes_Start(XAes *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_ReadReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_AP_CTRL) & 0x80;
    XAes_WriteReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XAes_IsDone(XAes *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_ReadReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XAes_IsIdle(XAes *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_ReadReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XAes_IsReady(XAes *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_ReadReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XAes_EnableAutoRestart(XAes *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XAes_DisableAutoRestart(XAes *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_AP_CTRL, 0);
}

u32 XAes_Get_return(XAes *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_ReadReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_AP_RETURN);
    return Data;
}
void XAes_Set_sourceAddress(XAes *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_SOURCEADDRESS_DATA, Data);
}

u32 XAes_Get_sourceAddress(XAes *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_ReadReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_SOURCEADDRESS_DATA);
    return Data;
}

void XAes_Set_sourceAddress_vld(XAes *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_SOURCEADDRESS_CTRL, 1);
}

u32 XAes_Get_sourceAddress_vld(XAes *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_ReadReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_SOURCEADDRESS_CTRL);
    return Data & 0x1;
}

void XAes_Set_key_in_V(XAes *InstancePtr, XAes_Key_in_v Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_KEY_IN_V_DATA + 0, Data.word_0);
    XAes_WriteReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_KEY_IN_V_DATA + 4, Data.word_1);
    XAes_WriteReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_KEY_IN_V_DATA + 8, Data.word_2);
    XAes_WriteReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_KEY_IN_V_DATA + 12, Data.word_3);
}

XAes_Key_in_v XAes_Get_key_in_V(XAes *InstancePtr) {
    XAes_Key_in_v Data;

    Data.word_0 = XAes_ReadReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_KEY_IN_V_DATA + 0);
    Data.word_1 = XAes_ReadReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_KEY_IN_V_DATA + 4);
    Data.word_2 = XAes_ReadReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_KEY_IN_V_DATA + 8);
    Data.word_3 = XAes_ReadReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_KEY_IN_V_DATA + 12);
    return Data;
}

void XAes_Set_key_in_V_vld(XAes *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_KEY_IN_V_CTRL, 1);
}

u32 XAes_Get_key_in_V_vld(XAes *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_ReadReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_KEY_IN_V_CTRL);
    return Data & 0x1;
}

void XAes_Set_iv_V(XAes *InstancePtr, XAes_Iv_v Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_IV_V_DATA + 0, Data.word_0);
    XAes_WriteReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_IV_V_DATA + 4, Data.word_1);
    XAes_WriteReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_IV_V_DATA + 8, Data.word_2);
    XAes_WriteReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_IV_V_DATA + 12, Data.word_3);
}

XAes_Iv_v XAes_Get_iv_V(XAes *InstancePtr) {
    XAes_Iv_v Data;

    Data.word_0 = XAes_ReadReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_IV_V_DATA + 0);
    Data.word_1 = XAes_ReadReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_IV_V_DATA + 4);
    Data.word_2 = XAes_ReadReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_IV_V_DATA + 8);
    Data.word_3 = XAes_ReadReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_IV_V_DATA + 12);
    return Data;
}

void XAes_Set_iv_V_vld(XAes *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_IV_V_CTRL, 1);
}

u32 XAes_Get_iv_V_vld(XAes *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_ReadReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_IV_V_CTRL);
    return Data & 0x1;
}

void XAes_Set_destinationAddress(XAes *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_DESTINATIONADDRESS_DATA, Data);
}

u32 XAes_Get_destinationAddress(XAes *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_ReadReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_DESTINATIONADDRESS_DATA);
    return Data;
}

void XAes_Set_destinationAddress_vld(XAes *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_DESTINATIONADDRESS_CTRL, 1);
}

u32 XAes_Get_destinationAddress_vld(XAes *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_ReadReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_DESTINATIONADDRESS_CTRL);
    return Data & 0x1;
}

void XAes_Set_numBytes(XAes *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_NUMBYTES_DATA, Data);
}

u32 XAes_Get_numBytes(XAes *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_ReadReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_NUMBYTES_DATA);
    return Data;
}

void XAes_Set_numBytes_vld(XAes *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_NUMBYTES_CTRL, 1);
}

u32 XAes_Get_numBytes_vld(XAes *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_ReadReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_NUMBYTES_CTRL);
    return Data & 0x1;
}

void XAes_Set_mode(XAes *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_MODE_DATA, Data);
}

u32 XAes_Get_mode(XAes *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_ReadReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_MODE_DATA);
    return Data;
}

void XAes_Set_mode_vld(XAes *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_MODE_CTRL, 1);
}

u32 XAes_Get_mode_vld(XAes *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_ReadReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_MODE_CTRL);
    return Data & 0x1;
}

void XAes_InterruptGlobalEnable(XAes *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_GIE, 1);
}

void XAes_InterruptGlobalDisable(XAes *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_GIE, 0);
}

void XAes_InterruptEnable(XAes *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XAes_ReadReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_IER);
    XAes_WriteReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_IER, Register | Mask);
}

void XAes_InterruptDisable(XAes *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XAes_ReadReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_IER);
    XAes_WriteReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_IER, Register & (~Mask));
}

void XAes_InterruptClear(XAes *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_ISR, Mask);
}

u32 XAes_InterruptGetEnabled(XAes *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XAes_ReadReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_IER);
}

u32 XAes_InterruptGetStatus(XAes *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XAes_ReadReg(InstancePtr->Axilites_BaseAddress, XAES_AXILITES_ADDR_ISR);
}

