// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XAES_H
#define XAES_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xaes_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XAes_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XAes;

typedef struct {
    u32 word_0;
    u32 word_1;
    u32 word_2;
    u32 word_3;
} XAes_Key_in_v;

typedef struct {
    u32 word_0;
    u32 word_1;
    u32 word_2;
    u32 word_3;
} XAes_Iv_v;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XAes_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XAes_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XAes_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XAes_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XAes_Initialize(XAes *InstancePtr, u16 DeviceId);
XAes_Config* XAes_LookupConfig(u16 DeviceId);
int XAes_CfgInitialize(XAes *InstancePtr, XAes_Config *ConfigPtr);
#else
int XAes_Initialize(XAes *InstancePtr, const char* InstanceName);
int XAes_Release(XAes *InstancePtr);
#endif

void XAes_Start(XAes *InstancePtr);
u32 XAes_IsDone(XAes *InstancePtr);
u32 XAes_IsIdle(XAes *InstancePtr);
u32 XAes_IsReady(XAes *InstancePtr);
void XAes_EnableAutoRestart(XAes *InstancePtr);
void XAes_DisableAutoRestart(XAes *InstancePtr);
u32 XAes_Get_return(XAes *InstancePtr);

void XAes_Set_sourceAddress(XAes *InstancePtr, u32 Data);
u32 XAes_Get_sourceAddress(XAes *InstancePtr);
void XAes_Set_sourceAddress_vld(XAes *InstancePtr);
u32 XAes_Get_sourceAddress_vld(XAes *InstancePtr);
void XAes_Set_key_in_V(XAes *InstancePtr, XAes_Key_in_v Data);
XAes_Key_in_v XAes_Get_key_in_V(XAes *InstancePtr);
void XAes_Set_key_in_V_vld(XAes *InstancePtr);
u32 XAes_Get_key_in_V_vld(XAes *InstancePtr);
void XAes_Set_iv_V(XAes *InstancePtr, XAes_Iv_v Data);
XAes_Iv_v XAes_Get_iv_V(XAes *InstancePtr);
void XAes_Set_iv_V_vld(XAes *InstancePtr);
u32 XAes_Get_iv_V_vld(XAes *InstancePtr);
void XAes_Set_destinationAddress(XAes *InstancePtr, u32 Data);
u32 XAes_Get_destinationAddress(XAes *InstancePtr);
void XAes_Set_destinationAddress_vld(XAes *InstancePtr);
u32 XAes_Get_destinationAddress_vld(XAes *InstancePtr);
void XAes_Set_numBytes(XAes *InstancePtr, u32 Data);
u32 XAes_Get_numBytes(XAes *InstancePtr);
void XAes_Set_numBytes_vld(XAes *InstancePtr);
u32 XAes_Get_numBytes_vld(XAes *InstancePtr);
void XAes_Set_mode(XAes *InstancePtr, u32 Data);
u32 XAes_Get_mode(XAes *InstancePtr);
void XAes_Set_mode_vld(XAes *InstancePtr);
u32 XAes_Get_mode_vld(XAes *InstancePtr);

void XAes_InterruptGlobalEnable(XAes *InstancePtr);
void XAes_InterruptGlobalDisable(XAes *InstancePtr);
void XAes_InterruptEnable(XAes *InstancePtr, u32 Mask);
void XAes_InterruptDisable(XAes *InstancePtr, u32 Mask);
void XAes_InterruptClear(XAes *InstancePtr, u32 Mask);
u32 XAes_InterruptGetEnabled(XAes *InstancePtr);
u32 XAes_InterruptGetStatus(XAes *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
