// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of ap_return
//        bit 31~0 - ap_return[31:0] (Read)
// 0x20 ~
// 0x3f : Memory 'mypublic' (32 * 8b)
//        Word n : bit [ 7: 0] - mypublic[4n]
//                 bit [15: 8] - mypublic[4n+1]
//                 bit [23:16] - mypublic[4n+2]
//                 bit [31:24] - mypublic[4n+3]
// 0x40 ~
// 0x5f : Memory 'secret' (32 * 8b)
//        Word n : bit [ 7: 0] - secret[4n]
//                 bit [15: 8] - secret[4n+1]
//                 bit [23:16] - secret[4n+2]
//                 bit [31:24] - secret[4n+3]
// 0x60 ~
// 0x7f : Memory 'basepoint' (32 * 8b)
//        Word n : bit [ 7: 0] - basepoint[4n]
//                 bit [15: 8] - basepoint[4n+1]
//                 bit [23:16] - basepoint[4n+2]
//                 bit [31:24] - basepoint[4n+3]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XCURVE25519_DONNA_AXILITES_ADDR_AP_CTRL        0x00
#define XCURVE25519_DONNA_AXILITES_ADDR_GIE            0x04
#define XCURVE25519_DONNA_AXILITES_ADDR_IER            0x08
#define XCURVE25519_DONNA_AXILITES_ADDR_ISR            0x0c
#define XCURVE25519_DONNA_AXILITES_ADDR_AP_RETURN      0x10
#define XCURVE25519_DONNA_AXILITES_BITS_AP_RETURN      32
#define XCURVE25519_DONNA_AXILITES_ADDR_MYPUBLIC_BASE  0x20
#define XCURVE25519_DONNA_AXILITES_ADDR_MYPUBLIC_HIGH  0x3f
#define XCURVE25519_DONNA_AXILITES_WIDTH_MYPUBLIC      8
#define XCURVE25519_DONNA_AXILITES_DEPTH_MYPUBLIC      32
#define XCURVE25519_DONNA_AXILITES_ADDR_SECRET_BASE    0x40
#define XCURVE25519_DONNA_AXILITES_ADDR_SECRET_HIGH    0x5f
#define XCURVE25519_DONNA_AXILITES_WIDTH_SECRET        8
#define XCURVE25519_DONNA_AXILITES_DEPTH_SECRET        32
#define XCURVE25519_DONNA_AXILITES_ADDR_BASEPOINT_BASE 0x60
#define XCURVE25519_DONNA_AXILITES_ADDR_BASEPOINT_HIGH 0x7f
#define XCURVE25519_DONNA_AXILITES_WIDTH_BASEPOINT     8
#define XCURVE25519_DONNA_AXILITES_DEPTH_BASEPOINT     32

