// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xmemory_scanner_ddr.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XMemory_scanner_ddr_CfgInitialize(XMemory_scanner_ddr *InstancePtr, XMemory_scanner_ddr_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Lite_BaseAddress = ConfigPtr->Lite_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XMemory_scanner_ddr_Start(XMemory_scanner_ddr *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ddr_ReadReg(InstancePtr->Lite_BaseAddress, XMEMORY_SCANNER_DDR_LITE_ADDR_AP_CTRL) & 0x80;
    XMemory_scanner_ddr_WriteReg(InstancePtr->Lite_BaseAddress, XMEMORY_SCANNER_DDR_LITE_ADDR_AP_CTRL, Data | 0x01);
}

u32 XMemory_scanner_ddr_IsDone(XMemory_scanner_ddr *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ddr_ReadReg(InstancePtr->Lite_BaseAddress, XMEMORY_SCANNER_DDR_LITE_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XMemory_scanner_ddr_IsIdle(XMemory_scanner_ddr *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ddr_ReadReg(InstancePtr->Lite_BaseAddress, XMEMORY_SCANNER_DDR_LITE_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XMemory_scanner_ddr_IsReady(XMemory_scanner_ddr *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ddr_ReadReg(InstancePtr->Lite_BaseAddress, XMEMORY_SCANNER_DDR_LITE_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XMemory_scanner_ddr_EnableAutoRestart(XMemory_scanner_ddr *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_ddr_WriteReg(InstancePtr->Lite_BaseAddress, XMEMORY_SCANNER_DDR_LITE_ADDR_AP_CTRL, 0x80);
}

void XMemory_scanner_ddr_DisableAutoRestart(XMemory_scanner_ddr *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_ddr_WriteReg(InstancePtr->Lite_BaseAddress, XMEMORY_SCANNER_DDR_LITE_ADDR_AP_CTRL, 0);
}

u32 XMemory_scanner_ddr_GetReturn(XMemory_scanner_ddr *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ddr_ReadReg(InstancePtr->Lite_BaseAddress, XMEMORY_SCANNER_DDR_LITE_ADDR_AP_RETURN);
    return Data;
}
void XMemory_scanner_ddr_SetSearch_string_v(XMemory_scanner_ddr *InstancePtr, XMemory_scanner_ddr_Search_string_v Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_ddr_WriteReg(InstancePtr->Lite_BaseAddress, XMEMORY_SCANNER_DDR_LITE_ADDR_SEARCH_STRING_V_DATA + 0, Data.word_0);
    XMemory_scanner_ddr_WriteReg(InstancePtr->Lite_BaseAddress, XMEMORY_SCANNER_DDR_LITE_ADDR_SEARCH_STRING_V_DATA + 4, Data.word_1);
    XMemory_scanner_ddr_WriteReg(InstancePtr->Lite_BaseAddress, XMEMORY_SCANNER_DDR_LITE_ADDR_SEARCH_STRING_V_DATA + 8, Data.word_2);
    XMemory_scanner_ddr_WriteReg(InstancePtr->Lite_BaseAddress, XMEMORY_SCANNER_DDR_LITE_ADDR_SEARCH_STRING_V_DATA + 12, Data.word_3);
}

XMemory_scanner_ddr_Search_string_v XMemory_scanner_ddr_GetSearch_string_v(XMemory_scanner_ddr *InstancePtr) {
    XMemory_scanner_ddr_Search_string_v Data;

    Data.word_0 = XMemory_scanner_ddr_ReadReg(InstancePtr->Lite_BaseAddress, XMEMORY_SCANNER_DDR_LITE_ADDR_SEARCH_STRING_V_DATA + 0);
    Data.word_1 = XMemory_scanner_ddr_ReadReg(InstancePtr->Lite_BaseAddress, XMEMORY_SCANNER_DDR_LITE_ADDR_SEARCH_STRING_V_DATA + 4);
    Data.word_2 = XMemory_scanner_ddr_ReadReg(InstancePtr->Lite_BaseAddress, XMEMORY_SCANNER_DDR_LITE_ADDR_SEARCH_STRING_V_DATA + 8);
    Data.word_3 = XMemory_scanner_ddr_ReadReg(InstancePtr->Lite_BaseAddress, XMEMORY_SCANNER_DDR_LITE_ADDR_SEARCH_STRING_V_DATA + 12);
    return Data;
}

void XMemory_scanner_ddr_SetSearch_string_vVld(XMemory_scanner_ddr *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_ddr_WriteReg(InstancePtr->Lite_BaseAddress, XMEMORY_SCANNER_DDR_LITE_ADDR_SEARCH_STRING_V_CTRL, 1);
}

u32 XMemory_scanner_ddr_GetSearch_string_vVld(XMemory_scanner_ddr *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ddr_ReadReg(InstancePtr->Lite_BaseAddress, XMEMORY_SCANNER_DDR_LITE_ADDR_SEARCH_STRING_V_CTRL);
    return Data & 0x1;
}

u32 XMemory_scanner_ddr_GetCount_out(XMemory_scanner_ddr *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ddr_ReadReg(InstancePtr->Lite_BaseAddress, XMEMORY_SCANNER_DDR_LITE_ADDR_COUNT_OUT_DATA);
    return Data;
}

u32 XMemory_scanner_ddr_GetCount_outVld(XMemory_scanner_ddr *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ddr_ReadReg(InstancePtr->Lite_BaseAddress, XMEMORY_SCANNER_DDR_LITE_ADDR_COUNT_OUT_CTRL);
    return Data & 0x1;
}

void XMemory_scanner_ddr_InterruptGlobalEnable(XMemory_scanner_ddr *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_ddr_WriteReg(InstancePtr->Lite_BaseAddress, XMEMORY_SCANNER_DDR_LITE_ADDR_GIE, 1);
}

void XMemory_scanner_ddr_InterruptGlobalDisable(XMemory_scanner_ddr *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_ddr_WriteReg(InstancePtr->Lite_BaseAddress, XMEMORY_SCANNER_DDR_LITE_ADDR_GIE, 0);
}

void XMemory_scanner_ddr_InterruptEnable(XMemory_scanner_ddr *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMemory_scanner_ddr_ReadReg(InstancePtr->Lite_BaseAddress, XMEMORY_SCANNER_DDR_LITE_ADDR_IER);
    XMemory_scanner_ddr_WriteReg(InstancePtr->Lite_BaseAddress, XMEMORY_SCANNER_DDR_LITE_ADDR_IER, Register | Mask);
}

void XMemory_scanner_ddr_InterruptDisable(XMemory_scanner_ddr *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMemory_scanner_ddr_ReadReg(InstancePtr->Lite_BaseAddress, XMEMORY_SCANNER_DDR_LITE_ADDR_IER);
    XMemory_scanner_ddr_WriteReg(InstancePtr->Lite_BaseAddress, XMEMORY_SCANNER_DDR_LITE_ADDR_IER, Register & (~Mask));
}

void XMemory_scanner_ddr_InterruptClear(XMemory_scanner_ddr *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_ddr_WriteReg(InstancePtr->Lite_BaseAddress, XMEMORY_SCANNER_DDR_LITE_ADDR_ISR, Mask);
}

u32 XMemory_scanner_ddr_InterruptGetEnabled(XMemory_scanner_ddr *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMemory_scanner_ddr_ReadReg(InstancePtr->Lite_BaseAddress, XMEMORY_SCANNER_DDR_LITE_ADDR_IER);
}

u32 XMemory_scanner_ddr_InterruptGetStatus(XMemory_scanner_ddr *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMemory_scanner_ddr_ReadReg(InstancePtr->Lite_BaseAddress, XMEMORY_SCANNER_DDR_LITE_ADDR_ISR);
}

