// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XMEMORY_SCANNER_DDR_H
#define XMEMORY_SCANNER_DDR_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xmemory_scanner_ddr_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Lite_BaseAddress;
} XMemory_scanner_ddr_Config;
#endif

typedef struct {
    u32 Lite_BaseAddress;
    u32 IsReady;
} XMemory_scanner_ddr;

typedef struct {
    u32 word_0;
    u32 word_1;
    u32 word_2;
    u32 word_3;
} XMemory_scanner_ddr_Search_string_v;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XMemory_scanner_ddr_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XMemory_scanner_ddr_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XMemory_scanner_ddr_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XMemory_scanner_ddr_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XMemory_scanner_ddr_Initialize(XMemory_scanner_ddr *InstancePtr, u16 DeviceId);
XMemory_scanner_ddr_Config* XMemory_scanner_ddr_LookupConfig(u16 DeviceId);
int XMemory_scanner_ddr_CfgInitialize(XMemory_scanner_ddr *InstancePtr, XMemory_scanner_ddr_Config *ConfigPtr);
#else
int XMemory_scanner_ddr_Initialize(XMemory_scanner_ddr *InstancePtr, const char* InstanceName);
int XMemory_scanner_ddr_Release(XMemory_scanner_ddr *InstancePtr);
#endif

void XMemory_scanner_ddr_Start(XMemory_scanner_ddr *InstancePtr);
u32 XMemory_scanner_ddr_IsDone(XMemory_scanner_ddr *InstancePtr);
u32 XMemory_scanner_ddr_IsIdle(XMemory_scanner_ddr *InstancePtr);
u32 XMemory_scanner_ddr_IsReady(XMemory_scanner_ddr *InstancePtr);
void XMemory_scanner_ddr_EnableAutoRestart(XMemory_scanner_ddr *InstancePtr);
void XMemory_scanner_ddr_DisableAutoRestart(XMemory_scanner_ddr *InstancePtr);
u32 XMemory_scanner_ddr_GetReturn(XMemory_scanner_ddr *InstancePtr);

void XMemory_scanner_ddr_SetSearch_string_v(XMemory_scanner_ddr *InstancePtr, XMemory_scanner_ddr_Search_string_v Data);
XMemory_scanner_ddr_Search_string_v XMemory_scanner_ddr_GetSearch_string_v(XMemory_scanner_ddr *InstancePtr);
void XMemory_scanner_ddr_SetSearch_string_vVld(XMemory_scanner_ddr *InstancePtr);
u32 XMemory_scanner_ddr_GetSearch_string_vVld(XMemory_scanner_ddr *InstancePtr);
u32 XMemory_scanner_ddr_GetCount_out(XMemory_scanner_ddr *InstancePtr);
u32 XMemory_scanner_ddr_GetCount_outVld(XMemory_scanner_ddr *InstancePtr);

void XMemory_scanner_ddr_InterruptGlobalEnable(XMemory_scanner_ddr *InstancePtr);
void XMemory_scanner_ddr_InterruptGlobalDisable(XMemory_scanner_ddr *InstancePtr);
void XMemory_scanner_ddr_InterruptEnable(XMemory_scanner_ddr *InstancePtr, u32 Mask);
void XMemory_scanner_ddr_InterruptDisable(XMemory_scanner_ddr *InstancePtr, u32 Mask);
void XMemory_scanner_ddr_InterruptClear(XMemory_scanner_ddr *InstancePtr, u32 Mask);
u32 XMemory_scanner_ddr_InterruptGetEnabled(XMemory_scanner_ddr *InstancePtr);
u32 XMemory_scanner_ddr_InterruptGetStatus(XMemory_scanner_ddr *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
