// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xaes.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XAes_CfgInitialize(XAes *InstancePtr, XAes_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axi4lites_BaseAddress = ConfigPtr->Axi4lites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XAes_SetSourceaddress(XAes *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Axi4lites_BaseAddress, XAES_AXI4LITES_ADDR_SOURCEADDRESS_DATA, Data);
}

u32 XAes_GetSourceaddress(XAes *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_ReadReg(InstancePtr->Axi4lites_BaseAddress, XAES_AXI4LITES_ADDR_SOURCEADDRESS_DATA);
    return Data;
}

void XAes_SetSourceaddressVld(XAes *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Axi4lites_BaseAddress, XAES_AXI4LITES_ADDR_SOURCEADDRESS_CTRL, 1);
}

u32 XAes_GetSourceaddressVld(XAes *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_ReadReg(InstancePtr->Axi4lites_BaseAddress, XAES_AXI4LITES_ADDR_SOURCEADDRESS_CTRL);
    return Data & 0x1;
}

void XAes_SetKey_in_v(XAes *InstancePtr, XAes_Key_in_v Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Axi4lites_BaseAddress, XAES_AXI4LITES_ADDR_KEY_IN_V_DATA + 0, Data.word_0);
    XAes_WriteReg(InstancePtr->Axi4lites_BaseAddress, XAES_AXI4LITES_ADDR_KEY_IN_V_DATA + 4, Data.word_1);
    XAes_WriteReg(InstancePtr->Axi4lites_BaseAddress, XAES_AXI4LITES_ADDR_KEY_IN_V_DATA + 8, Data.word_2);
    XAes_WriteReg(InstancePtr->Axi4lites_BaseAddress, XAES_AXI4LITES_ADDR_KEY_IN_V_DATA + 12, Data.word_3);
}

XAes_Key_in_v XAes_GetKey_in_v(XAes *InstancePtr) {
    XAes_Key_in_v Data;

    Data.word_0 = XAes_ReadReg(InstancePtr->Axi4lites_BaseAddress, XAES_AXI4LITES_ADDR_KEY_IN_V_DATA + 0);
    Data.word_1 = XAes_ReadReg(InstancePtr->Axi4lites_BaseAddress, XAES_AXI4LITES_ADDR_KEY_IN_V_DATA + 4);
    Data.word_2 = XAes_ReadReg(InstancePtr->Axi4lites_BaseAddress, XAES_AXI4LITES_ADDR_KEY_IN_V_DATA + 8);
    Data.word_3 = XAes_ReadReg(InstancePtr->Axi4lites_BaseAddress, XAES_AXI4LITES_ADDR_KEY_IN_V_DATA + 12);
    return Data;
}

void XAes_SetKey_in_vVld(XAes *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Axi4lites_BaseAddress, XAES_AXI4LITES_ADDR_KEY_IN_V_CTRL, 1);
}

u32 XAes_GetKey_in_vVld(XAes *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_ReadReg(InstancePtr->Axi4lites_BaseAddress, XAES_AXI4LITES_ADDR_KEY_IN_V_CTRL);
    return Data & 0x1;
}

void XAes_SetDestinationaddress(XAes *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Axi4lites_BaseAddress, XAES_AXI4LITES_ADDR_DESTINATIONADDRESS_DATA, Data);
}

u32 XAes_GetDestinationaddress(XAes *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_ReadReg(InstancePtr->Axi4lites_BaseAddress, XAES_AXI4LITES_ADDR_DESTINATIONADDRESS_DATA);
    return Data;
}

void XAes_SetDestinationaddressVld(XAes *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Axi4lites_BaseAddress, XAES_AXI4LITES_ADDR_DESTINATIONADDRESS_CTRL, 1);
}

u32 XAes_GetDestinationaddressVld(XAes *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_ReadReg(InstancePtr->Axi4lites_BaseAddress, XAES_AXI4LITES_ADDR_DESTINATIONADDRESS_CTRL);
    return Data & 0x1;
}

void XAes_SetLength_r(XAes *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Axi4lites_BaseAddress, XAES_AXI4LITES_ADDR_LENGTH_R_DATA, Data);
}

u32 XAes_GetLength_r(XAes *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_ReadReg(InstancePtr->Axi4lites_BaseAddress, XAES_AXI4LITES_ADDR_LENGTH_R_DATA);
    return Data;
}

void XAes_SetLength_rVld(XAes *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Axi4lites_BaseAddress, XAES_AXI4LITES_ADDR_LENGTH_R_CTRL, 1);
}

u32 XAes_GetLength_rVld(XAes *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_ReadReg(InstancePtr->Axi4lites_BaseAddress, XAES_AXI4LITES_ADDR_LENGTH_R_CTRL);
    return Data & 0x1;
}

u32 XAes_GetFinished(XAes *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_ReadReg(InstancePtr->Axi4lites_BaseAddress, XAES_AXI4LITES_ADDR_FINISHED_DATA);
    return Data;
}

void XAes_SetFinishedAck(XAes *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Axi4lites_BaseAddress, XAES_AXI4LITES_ADDR_FINISHED_CTRL, 2);
}

u32 XAes_GetFinishedAck(XAes *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_ReadReg(InstancePtr->Axi4lites_BaseAddress, XAES_AXI4LITES_ADDR_FINISHED_CTRL);
    return (Data >> 1) & 0x1;
}

