// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XAES_H
#define XAES_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xaes_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axi4lites_BaseAddress;
} XAes_Config;
#endif

typedef struct {
    u32 Axi4lites_BaseAddress;
    u32 IsReady;
} XAes;

typedef struct {
    u32 word_0;
    u32 word_1;
    u32 word_2;
    u32 word_3;
} XAes_Key_in_v;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XAes_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XAes_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XAes_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XAes_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XAes_Initialize(XAes *InstancePtr, u16 DeviceId);
XAes_Config* XAes_LookupConfig(u16 DeviceId);
int XAes_CfgInitialize(XAes *InstancePtr, XAes_Config *ConfigPtr);
#else
int XAes_Initialize(XAes *InstancePtr, const char* InstanceName);
int XAes_Release(XAes *InstancePtr);
#endif


void XAes_SetSourceaddress(XAes *InstancePtr, u32 Data);
u32 XAes_GetSourceaddress(XAes *InstancePtr);
void XAes_SetSourceaddressVld(XAes *InstancePtr);
u32 XAes_GetSourceaddressVld(XAes *InstancePtr);
void XAes_SetKey_in_v(XAes *InstancePtr, XAes_Key_in_v Data);
XAes_Key_in_v XAes_GetKey_in_v(XAes *InstancePtr);
void XAes_SetKey_in_vVld(XAes *InstancePtr);
u32 XAes_GetKey_in_vVld(XAes *InstancePtr);
void XAes_SetDestinationaddress(XAes *InstancePtr, u32 Data);
u32 XAes_GetDestinationaddress(XAes *InstancePtr);
void XAes_SetDestinationaddressVld(XAes *InstancePtr);
u32 XAes_GetDestinationaddressVld(XAes *InstancePtr);
void XAes_SetLength_r(XAes *InstancePtr, u32 Data);
u32 XAes_GetLength_r(XAes *InstancePtr);
void XAes_SetLength_rVld(XAes *InstancePtr);
u32 XAes_GetLength_rVld(XAes *InstancePtr);
u32 XAes_GetFinished(XAes *InstancePtr);
void XAes_SetFinishedAck(XAes *InstancePtr);
u32 XAes_GetFinishedAck(XAes *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
