// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// AXI4LiteS
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Control signal of sourceAddress
//        bit 0  - sourceAddress_ap_vld (Read/Write/SC)
//        others - reserved
// 0x14 : Data signal of sourceAddress
//        bit 31~0 - sourceAddress[31:0] (Read/Write)
// 0x18 : Control signal of key_in_V
//        bit 0  - key_in_V_ap_vld (Read/Write/SC)
//        others - reserved
// 0x1c : Data signal of key_in_V
//        bit 31~0 - key_in_V[31:0] (Read/Write)
// 0x20 : Data signal of key_in_V
//        bit 31~0 - key_in_V[63:32] (Read/Write)
// 0x24 : Data signal of key_in_V
//        bit 31~0 - key_in_V[95:64] (Read/Write)
// 0x28 : Data signal of key_in_V
//        bit 31~0 - key_in_V[127:96] (Read/Write)
// 0x2c : Control signal of destinationAddress
//        bit 0  - destinationAddress_ap_vld (Read/Write/SC)
//        others - reserved
// 0x30 : Data signal of destinationAddress
//        bit 31~0 - destinationAddress[31:0] (Read/Write)
// 0x34 : Control signal of length_r
//        bit 0  - length_r_ap_vld (Read/Write/SC)
//        others - reserved
// 0x38 : Data signal of length_r
//        bit 31~0 - length_r[31:0] (Read/Write)
// 0x3c : Control signal of finished
//        bit 1  - finished_ap_ack (Read/Write/SC)
//        others - reserved
// 0x40 : Data signal of finished
//        bit 0  - finished[0] (Read)
//        others - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XAES_AXI4LITES_ADDR_SOURCEADDRESS_CTRL      0x10
#define XAES_AXI4LITES_ADDR_SOURCEADDRESS_DATA      0x14
#define XAES_AXI4LITES_BITS_SOURCEADDRESS_DATA      32
#define XAES_AXI4LITES_ADDR_KEY_IN_V_CTRL           0x18
#define XAES_AXI4LITES_ADDR_KEY_IN_V_DATA           0x1c
#define XAES_AXI4LITES_BITS_KEY_IN_V_DATA           128
#define XAES_AXI4LITES_ADDR_DESTINATIONADDRESS_CTRL 0x2c
#define XAES_AXI4LITES_ADDR_DESTINATIONADDRESS_DATA 0x30
#define XAES_AXI4LITES_BITS_DESTINATIONADDRESS_DATA 32
#define XAES_AXI4LITES_ADDR_LENGTH_R_CTRL           0x34
#define XAES_AXI4LITES_ADDR_LENGTH_R_DATA           0x38
#define XAES_AXI4LITES_BITS_LENGTH_R_DATA           32
#define XAES_AXI4LITES_ADDR_FINISHED_CTRL           0x3c
#define XAES_AXI4LITES_ADDR_FINISHED_DATA           0x40
#define XAES_AXI4LITES_BITS_FINISHED_DATA           1

