// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xtest_direct_dma.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XTest_direct_dma_CfgInitialize(XTest_direct_dma *InstancePtr, XTest_direct_dma_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XTest_direct_dma_Set_sourceAddress(XTest_direct_dma *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTest_direct_dma_WriteReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_SOURCEADDRESS_DATA, Data);
}

u32 XTest_direct_dma_Get_sourceAddress(XTest_direct_dma *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTest_direct_dma_ReadReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_SOURCEADDRESS_DATA);
    return Data;
}

void XTest_direct_dma_Set_destinationAddress(XTest_direct_dma *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTest_direct_dma_WriteReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_DESTINATIONADDRESS_DATA, Data);
}

u32 XTest_direct_dma_Get_destinationAddress(XTest_direct_dma *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTest_direct_dma_ReadReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_DESTINATIONADDRESS_DATA);
    return Data;
}

