// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xreset_axi.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XReset_axi_CfgInitialize(XReset_axi *InstancePtr, XReset_axi_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axi4lites_BaseAddress = ConfigPtr->Axi4lites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XReset_axi_SetIn_reset(XReset_axi *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XReset_axi_WriteReg(InstancePtr->Axi4lites_BaseAddress, XRESET_AXI_AXI4LITES_ADDR_IN_RESET_DATA, Data);
}

u32 XReset_axi_GetIn_reset(XReset_axi *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XReset_axi_ReadReg(InstancePtr->Axi4lites_BaseAddress, XRESET_AXI_AXI4LITES_ADDR_IN_RESET_DATA);
    return Data;
}

