// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xmemory_scanner.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XMemory_scanner_CfgInitialize(XMemory_scanner *InstancePtr, XMemory_scanner_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XMemory_scanner_Start(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_AP_CTRL) & 0x80;
    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XMemory_scanner_IsDone(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XMemory_scanner_IsIdle(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XMemory_scanner_IsReady(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XMemory_scanner_EnableAutoRestart(XMemory_scanner *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XMemory_scanner_DisableAutoRestart(XMemory_scanner *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_AP_CTRL, 0);
}

u32 XMemory_scanner_Get_return(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_AP_RETURN);
    return Data;
}
void XMemory_scanner_Set_search_string_V(XMemory_scanner *InstancePtr, XMemory_scanner_Search_string_v Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_V_DATA + 0, Data.word_0);
    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_V_DATA + 4, Data.word_1);
    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_V_DATA + 8, Data.word_2);
    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_V_DATA + 12, Data.word_3);
}

XMemory_scanner_Search_string_v XMemory_scanner_Get_search_string_V(XMemory_scanner *InstancePtr) {
    XMemory_scanner_Search_string_v Data;

    Data.word_0 = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_V_DATA + 0);
    Data.word_1 = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_V_DATA + 4);
    Data.word_2 = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_V_DATA + 8);
    Data.word_3 = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_V_DATA + 12);
    return Data;
}

void XMemory_scanner_Set_search_string_V_vld(XMemory_scanner *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_V_CTRL, 1);
}

u32 XMemory_scanner_Get_search_string_V_vld(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_V_CTRL);
    return Data & 0x1;
}

u32 XMemory_scanner_Get_count_out(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_COUNT_OUT_DATA);
    return Data;
}

u32 XMemory_scanner_Get_count_out_vld(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_COUNT_OUT_CTRL);
    return Data & 0x1;
}

void XMemory_scanner_InterruptGlobalEnable(XMemory_scanner *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_GIE, 1);
}

void XMemory_scanner_InterruptGlobalDisable(XMemory_scanner *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_GIE, 0);
}

void XMemory_scanner_InterruptEnable(XMemory_scanner *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_IER);
    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_IER, Register | Mask);
}

void XMemory_scanner_InterruptDisable(XMemory_scanner *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_IER);
    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_IER, Register & (~Mask));
}

void XMemory_scanner_InterruptClear(XMemory_scanner *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_ISR, Mask);
}

u32 XMemory_scanner_InterruptGetEnabled(XMemory_scanner *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_IER);
}

u32 XMemory_scanner_InterruptGetStatus(XMemory_scanner *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_ISR);
}

