// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xmemory_scanner.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XMemory_scanner_CfgInitialize(XMemory_scanner *InstancePtr, XMemory_scanner_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XMemory_scanner_Start(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_AP_CTRL) & 0x80;
    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XMemory_scanner_IsDone(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XMemory_scanner_IsIdle(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XMemory_scanner_IsReady(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XMemory_scanner_EnableAutoRestart(XMemory_scanner *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XMemory_scanner_DisableAutoRestart(XMemory_scanner *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_AP_CTRL, 0);
}

u32 XMemory_scanner_Get_return(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_AP_RETURN);
    return Data;
}
void XMemory_scanner_Set_search_string_0(XMemory_scanner *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_0_DATA, Data);
}

u32 XMemory_scanner_Get_search_string_0(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_0_DATA);
    return Data;
}

void XMemory_scanner_Set_search_string_0_vld(XMemory_scanner *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_0_CTRL, 1);
}

u32 XMemory_scanner_Get_search_string_0_vld(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_0_CTRL);
    return Data & 0x1;
}

u32 XMemory_scanner_Get_search_string_0_ack(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_0_CTRL);
    return (Data >> 1) & 0x1;
}

void XMemory_scanner_Set_search_string_1(XMemory_scanner *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_1_DATA, Data);
}

u32 XMemory_scanner_Get_search_string_1(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_1_DATA);
    return Data;
}

void XMemory_scanner_Set_search_string_1_vld(XMemory_scanner *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_1_CTRL, 1);
}

u32 XMemory_scanner_Get_search_string_1_vld(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_1_CTRL);
    return Data & 0x1;
}

u32 XMemory_scanner_Get_search_string_1_ack(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_1_CTRL);
    return (Data >> 1) & 0x1;
}

void XMemory_scanner_Set_search_string_2(XMemory_scanner *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_2_DATA, Data);
}

u32 XMemory_scanner_Get_search_string_2(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_2_DATA);
    return Data;
}

void XMemory_scanner_Set_search_string_2_vld(XMemory_scanner *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_2_CTRL, 1);
}

u32 XMemory_scanner_Get_search_string_2_vld(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_2_CTRL);
    return Data & 0x1;
}

u32 XMemory_scanner_Get_search_string_2_ack(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_2_CTRL);
    return (Data >> 1) & 0x1;
}

void XMemory_scanner_Set_search_string_3(XMemory_scanner *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_3_DATA, Data);
}

u32 XMemory_scanner_Get_search_string_3(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_3_DATA);
    return Data;
}

void XMemory_scanner_Set_search_string_3_vld(XMemory_scanner *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_3_CTRL, 1);
}

u32 XMemory_scanner_Get_search_string_3_vld(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_3_CTRL);
    return Data & 0x1;
}

u32 XMemory_scanner_Get_search_string_3_ack(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_3_CTRL);
    return (Data >> 1) & 0x1;
}

void XMemory_scanner_Set_search_string_4(XMemory_scanner *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_4_DATA, Data);
}

u32 XMemory_scanner_Get_search_string_4(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_4_DATA);
    return Data;
}

void XMemory_scanner_Set_search_string_4_vld(XMemory_scanner *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_4_CTRL, 1);
}

u32 XMemory_scanner_Get_search_string_4_vld(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_4_CTRL);
    return Data & 0x1;
}

u32 XMemory_scanner_Get_search_string_4_ack(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_4_CTRL);
    return (Data >> 1) & 0x1;
}

void XMemory_scanner_Set_search_string_5(XMemory_scanner *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_5_DATA, Data);
}

u32 XMemory_scanner_Get_search_string_5(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_5_DATA);
    return Data;
}

void XMemory_scanner_Set_search_string_5_vld(XMemory_scanner *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_5_CTRL, 1);
}

u32 XMemory_scanner_Get_search_string_5_vld(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_5_CTRL);
    return Data & 0x1;
}

u32 XMemory_scanner_Get_search_string_5_ack(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_5_CTRL);
    return (Data >> 1) & 0x1;
}

void XMemory_scanner_Set_search_string_6(XMemory_scanner *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_6_DATA, Data);
}

u32 XMemory_scanner_Get_search_string_6(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_6_DATA);
    return Data;
}

void XMemory_scanner_Set_search_string_6_vld(XMemory_scanner *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_6_CTRL, 1);
}

u32 XMemory_scanner_Get_search_string_6_vld(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_6_CTRL);
    return Data & 0x1;
}

u32 XMemory_scanner_Get_search_string_6_ack(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_6_CTRL);
    return (Data >> 1) & 0x1;
}

void XMemory_scanner_Set_search_string_7(XMemory_scanner *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_7_DATA, Data);
}

u32 XMemory_scanner_Get_search_string_7(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_7_DATA);
    return Data;
}

void XMemory_scanner_Set_search_string_7_vld(XMemory_scanner *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_7_CTRL, 1);
}

u32 XMemory_scanner_Get_search_string_7_vld(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_7_CTRL);
    return Data & 0x1;
}

u32 XMemory_scanner_Get_search_string_7_ack(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_7_CTRL);
    return (Data >> 1) & 0x1;
}

void XMemory_scanner_Set_search_string_8(XMemory_scanner *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_8_DATA, Data);
}

u32 XMemory_scanner_Get_search_string_8(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_8_DATA);
    return Data;
}

void XMemory_scanner_Set_search_string_8_vld(XMemory_scanner *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_8_CTRL, 1);
}

u32 XMemory_scanner_Get_search_string_8_vld(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_8_CTRL);
    return Data & 0x1;
}

u32 XMemory_scanner_Get_search_string_8_ack(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_8_CTRL);
    return (Data >> 1) & 0x1;
}

void XMemory_scanner_Set_search_string_9(XMemory_scanner *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_9_DATA, Data);
}

u32 XMemory_scanner_Get_search_string_9(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_9_DATA);
    return Data;
}

void XMemory_scanner_Set_search_string_9_vld(XMemory_scanner *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_9_CTRL, 1);
}

u32 XMemory_scanner_Get_search_string_9_vld(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_9_CTRL);
    return Data & 0x1;
}

u32 XMemory_scanner_Get_search_string_9_ack(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_9_CTRL);
    return (Data >> 1) & 0x1;
}

void XMemory_scanner_Set_search_string_10(XMemory_scanner *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_10_DATA, Data);
}

u32 XMemory_scanner_Get_search_string_10(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_10_DATA);
    return Data;
}

void XMemory_scanner_Set_search_string_10_vld(XMemory_scanner *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_10_CTRL, 1);
}

u32 XMemory_scanner_Get_search_string_10_vld(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_10_CTRL);
    return Data & 0x1;
}

u32 XMemory_scanner_Get_search_string_10_ack(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_10_CTRL);
    return (Data >> 1) & 0x1;
}

void XMemory_scanner_Set_search_string_11(XMemory_scanner *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_11_DATA, Data);
}

u32 XMemory_scanner_Get_search_string_11(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_11_DATA);
    return Data;
}

void XMemory_scanner_Set_search_string_11_vld(XMemory_scanner *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_11_CTRL, 1);
}

u32 XMemory_scanner_Get_search_string_11_vld(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_11_CTRL);
    return Data & 0x1;
}

u32 XMemory_scanner_Get_search_string_11_ack(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_11_CTRL);
    return (Data >> 1) & 0x1;
}

void XMemory_scanner_Set_search_string_12(XMemory_scanner *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_12_DATA, Data);
}

u32 XMemory_scanner_Get_search_string_12(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_12_DATA);
    return Data;
}

void XMemory_scanner_Set_search_string_12_vld(XMemory_scanner *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_12_CTRL, 1);
}

u32 XMemory_scanner_Get_search_string_12_vld(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_12_CTRL);
    return Data & 0x1;
}

u32 XMemory_scanner_Get_search_string_12_ack(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_12_CTRL);
    return (Data >> 1) & 0x1;
}

void XMemory_scanner_Set_search_string_13(XMemory_scanner *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_13_DATA, Data);
}

u32 XMemory_scanner_Get_search_string_13(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_13_DATA);
    return Data;
}

void XMemory_scanner_Set_search_string_13_vld(XMemory_scanner *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_13_CTRL, 1);
}

u32 XMemory_scanner_Get_search_string_13_vld(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_13_CTRL);
    return Data & 0x1;
}

u32 XMemory_scanner_Get_search_string_13_ack(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_13_CTRL);
    return (Data >> 1) & 0x1;
}

void XMemory_scanner_Set_search_string_14(XMemory_scanner *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_14_DATA, Data);
}

u32 XMemory_scanner_Get_search_string_14(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_14_DATA);
    return Data;
}

void XMemory_scanner_Set_search_string_14_vld(XMemory_scanner *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_14_CTRL, 1);
}

u32 XMemory_scanner_Get_search_string_14_vld(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_14_CTRL);
    return Data & 0x1;
}

u32 XMemory_scanner_Get_search_string_14_ack(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_14_CTRL);
    return (Data >> 1) & 0x1;
}

void XMemory_scanner_Set_search_string_15(XMemory_scanner *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_15_DATA, Data);
}

u32 XMemory_scanner_Get_search_string_15(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_15_DATA);
    return Data;
}

void XMemory_scanner_Set_search_string_15_vld(XMemory_scanner *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_15_CTRL, 1);
}

u32 XMemory_scanner_Get_search_string_15_vld(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_15_CTRL);
    return Data & 0x1;
}

u32 XMemory_scanner_Get_search_string_15_ack(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_15_CTRL);
    return (Data >> 1) & 0x1;
}

void XMemory_scanner_Set_search_string_16(XMemory_scanner *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_16_DATA, Data);
}

u32 XMemory_scanner_Get_search_string_16(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_16_DATA);
    return Data;
}

void XMemory_scanner_Set_search_string_16_vld(XMemory_scanner *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_16_CTRL, 1);
}

u32 XMemory_scanner_Get_search_string_16_vld(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_16_CTRL);
    return Data & 0x1;
}

u32 XMemory_scanner_Get_search_string_16_ack(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_SEARCH_STRING_16_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XMemory_scanner_Get_count_out(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_COUNT_OUT_DATA);
    return Data;
}

u32 XMemory_scanner_Get_count_out_vld(XMemory_scanner *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_COUNT_OUT_CTRL);
    return Data & 0x1;
}

void XMemory_scanner_InterruptGlobalEnable(XMemory_scanner *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_GIE, 1);
}

void XMemory_scanner_InterruptGlobalDisable(XMemory_scanner *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_GIE, 0);
}

void XMemory_scanner_InterruptEnable(XMemory_scanner *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_IER);
    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_IER, Register | Mask);
}

void XMemory_scanner_InterruptDisable(XMemory_scanner *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_IER);
    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_IER, Register & (~Mask));
}

void XMemory_scanner_InterruptClear(XMemory_scanner *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMemory_scanner_WriteReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_ISR, Mask);
}

u32 XMemory_scanner_InterruptGetEnabled(XMemory_scanner *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_IER);
}

u32 XMemory_scanner_InterruptGetStatus(XMemory_scanner *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMemory_scanner_ReadReg(InstancePtr->Axilites_BaseAddress, XMEMORY_SCANNER_AXILITES_ADDR_ISR);
}

