// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xcrec.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XCrec_CfgInitialize(XCrec *InstancePtr, XCrec_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XCrec_Start(XCrec *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCrec_ReadReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_AP_CTRL) & 0x80;
    XCrec_WriteReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XCrec_IsDone(XCrec *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCrec_ReadReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XCrec_IsIdle(XCrec *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCrec_ReadReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XCrec_IsReady(XCrec *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCrec_ReadReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XCrec_EnableAutoRestart(XCrec *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCrec_WriteReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XCrec_DisableAutoRestart(XCrec *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCrec_WriteReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_AP_CTRL, 0);
}

void XCrec_Set_din_i_V(XCrec *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCrec_WriteReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_DIN_I_V_DATA, Data);
}

u32 XCrec_Get_din_i_V(XCrec *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCrec_ReadReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_DIN_I_V_DATA);
    return Data;
}

void XCrec_Set_din_q_V(XCrec *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCrec_WriteReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_DIN_Q_V_DATA, Data);
}

u32 XCrec_Get_din_q_V(XCrec *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCrec_ReadReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_DIN_Q_V_DATA);
    return Data;
}

u32 XCrec_Get_dout_mix_i_V(XCrec *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCrec_ReadReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_DOUT_MIX_I_V_DATA);
    return Data;
}

u32 XCrec_Get_dout_mix_q_V(XCrec *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCrec_ReadReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_DOUT_MIX_Q_V_DATA);
    return Data;
}

void XCrec_Set_ph_in_i_V(XCrec *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCrec_WriteReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_PH_IN_I_V_DATA, Data);
}

u32 XCrec_Get_ph_in_i_V(XCrec *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCrec_ReadReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_PH_IN_I_V_DATA);
    return Data;
}

void XCrec_Set_ph_in_q_V(XCrec *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCrec_WriteReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_PH_IN_Q_V_DATA, Data);
}

u32 XCrec_Get_ph_in_q_V(XCrec *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCrec_ReadReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_PH_IN_Q_V_DATA);
    return Data;
}

u32 XCrec_Get_ph_out_i_V(XCrec *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCrec_ReadReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_PH_OUT_I_V_DATA);
    return Data;
}

u32 XCrec_Get_ph_out_q_V(XCrec *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCrec_ReadReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_PH_OUT_Q_V_DATA);
    return Data;
}

u32 XCrec_Get_loop_integ_V(XCrec *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCrec_ReadReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_LOOP_INTEG_V_DATA);
    return Data;
}

void XCrec_Set_control_qam_V(XCrec *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCrec_WriteReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_CONTROL_QAM_V_DATA, Data);
}

u32 XCrec_Get_control_qam_V(XCrec *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCrec_ReadReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_CONTROL_QAM_V_DATA);
    return Data;
}

void XCrec_Set_control_lf_p(XCrec *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCrec_WriteReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_CONTROL_LF_P_DATA, Data);
}

u32 XCrec_Get_control_lf_p(XCrec *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCrec_ReadReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_CONTROL_LF_P_DATA);
    return Data;
}

void XCrec_Set_control_lf_i(XCrec *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCrec_WriteReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_CONTROL_LF_I_DATA, Data);
}

u32 XCrec_Get_control_lf_i(XCrec *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCrec_ReadReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_CONTROL_LF_I_DATA);
    return Data;
}

void XCrec_Set_control_lf_out_gain(XCrec *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCrec_WriteReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_CONTROL_LF_OUT_GAIN_DATA, Data);
}

u32 XCrec_Get_control_lf_out_gain(XCrec *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCrec_ReadReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_CONTROL_LF_OUT_GAIN_DATA);
    return Data;
}

void XCrec_Set_control_reg_clr(XCrec *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCrec_WriteReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_CONTROL_REG_CLR_DATA, Data);
}

u32 XCrec_Get_control_reg_clr(XCrec *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCrec_ReadReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_CONTROL_REG_CLR_DATA);
    return Data;
}

void XCrec_Set_control_reg_init_V(XCrec *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCrec_WriteReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_CONTROL_REG_INIT_V_DATA, Data);
}

u32 XCrec_Get_control_reg_init_V(XCrec *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCrec_ReadReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_CONTROL_REG_INIT_V_DATA);
    return Data;
}

void XCrec_InterruptGlobalEnable(XCrec *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCrec_WriteReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_GIE, 1);
}

void XCrec_InterruptGlobalDisable(XCrec *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCrec_WriteReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_GIE, 0);
}

void XCrec_InterruptEnable(XCrec *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XCrec_ReadReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_IER);
    XCrec_WriteReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_IER, Register | Mask);
}

void XCrec_InterruptDisable(XCrec *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XCrec_ReadReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_IER);
    XCrec_WriteReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_IER, Register & (~Mask));
}

void XCrec_InterruptClear(XCrec *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCrec_WriteReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_ISR, Mask);
}

u32 XCrec_InterruptGetEnabled(XCrec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCrec_ReadReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_IER);
}

u32 XCrec_InterruptGetStatus(XCrec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCrec_ReadReg(InstancePtr->Axilites_BaseAddress, XCREC_AXILITES_ADDR_ISR);
}

