// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of din_i_V
//        bit 15~0 - din_i_V[15:0] (Read/Write)
//        others   - reserved
// 0x14 : reserved
// 0x18 : Data signal of din_q_V
//        bit 15~0 - din_q_V[15:0] (Read/Write)
//        others   - reserved
// 0x1c : reserved
// 0x20 : Data signal of dout_mix_i_V
//        bit 15~0 - dout_mix_i_V[15:0] (Read)
//        others   - reserved
// 0x24 : reserved
// 0x28 : Data signal of dout_mix_q_V
//        bit 15~0 - dout_mix_q_V[15:0] (Read)
//        others   - reserved
// 0x2c : reserved
// 0x30 : Data signal of ph_in_i_V
//        bit 11~0 - ph_in_i_V[11:0] (Read/Write)
//        others   - reserved
// 0x34 : reserved
// 0x38 : Data signal of ph_in_q_V
//        bit 11~0 - ph_in_q_V[11:0] (Read/Write)
//        others   - reserved
// 0x3c : reserved
// 0x40 : Data signal of ph_out_i_V
//        bit 11~0 - ph_out_i_V[11:0] (Read)
//        others   - reserved
// 0x44 : reserved
// 0x48 : Data signal of ph_out_q_V
//        bit 11~0 - ph_out_q_V[11:0] (Read)
//        others   - reserved
// 0x4c : reserved
// 0x50 : Data signal of loop_integ_V
//        bit 27~0 - loop_integ_V[27:0] (Read)
//        others   - reserved
// 0x54 : reserved
// 0x58 : Data signal of control_qam_V
//        bit 1~0 - control_qam_V[1:0] (Read/Write)
//        others  - reserved
// 0x5c : reserved
// 0x60 : Data signal of control_lf_p
//        bit 7~0 - control_lf_p[7:0] (Read/Write)
//        others  - reserved
// 0x64 : reserved
// 0x68 : Data signal of control_lf_i
//        bit 7~0 - control_lf_i[7:0] (Read/Write)
//        others  - reserved
// 0x6c : reserved
// 0x70 : Data signal of control_lf_out_gain
//        bit 7~0 - control_lf_out_gain[7:0] (Read/Write)
//        others  - reserved
// 0x74 : reserved
// 0x78 : Data signal of control_reg_clr
//        bit 0  - control_reg_clr[0] (Read/Write)
//        others - reserved
// 0x7c : reserved
// 0x80 : Data signal of control_reg_init_V
//        bit 27~0 - control_reg_init_V[27:0] (Read/Write)
//        others   - reserved
// 0x84 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XCREC_AXILITES_ADDR_AP_CTRL                  0x00
#define XCREC_AXILITES_ADDR_GIE                      0x04
#define XCREC_AXILITES_ADDR_IER                      0x08
#define XCREC_AXILITES_ADDR_ISR                      0x0c
#define XCREC_AXILITES_ADDR_DIN_I_V_DATA             0x10
#define XCREC_AXILITES_BITS_DIN_I_V_DATA             16
#define XCREC_AXILITES_ADDR_DIN_Q_V_DATA             0x18
#define XCREC_AXILITES_BITS_DIN_Q_V_DATA             16
#define XCREC_AXILITES_ADDR_DOUT_MIX_I_V_DATA        0x20
#define XCREC_AXILITES_BITS_DOUT_MIX_I_V_DATA        16
#define XCREC_AXILITES_ADDR_DOUT_MIX_Q_V_DATA        0x28
#define XCREC_AXILITES_BITS_DOUT_MIX_Q_V_DATA        16
#define XCREC_AXILITES_ADDR_PH_IN_I_V_DATA           0x30
#define XCREC_AXILITES_BITS_PH_IN_I_V_DATA           12
#define XCREC_AXILITES_ADDR_PH_IN_Q_V_DATA           0x38
#define XCREC_AXILITES_BITS_PH_IN_Q_V_DATA           12
#define XCREC_AXILITES_ADDR_PH_OUT_I_V_DATA          0x40
#define XCREC_AXILITES_BITS_PH_OUT_I_V_DATA          12
#define XCREC_AXILITES_ADDR_PH_OUT_Q_V_DATA          0x48
#define XCREC_AXILITES_BITS_PH_OUT_Q_V_DATA          12
#define XCREC_AXILITES_ADDR_LOOP_INTEG_V_DATA        0x50
#define XCREC_AXILITES_BITS_LOOP_INTEG_V_DATA        28
#define XCREC_AXILITES_ADDR_CONTROL_QAM_V_DATA       0x58
#define XCREC_AXILITES_BITS_CONTROL_QAM_V_DATA       2
#define XCREC_AXILITES_ADDR_CONTROL_LF_P_DATA        0x60
#define XCREC_AXILITES_BITS_CONTROL_LF_P_DATA        8
#define XCREC_AXILITES_ADDR_CONTROL_LF_I_DATA        0x68
#define XCREC_AXILITES_BITS_CONTROL_LF_I_DATA        8
#define XCREC_AXILITES_ADDR_CONTROL_LF_OUT_GAIN_DATA 0x70
#define XCREC_AXILITES_BITS_CONTROL_LF_OUT_GAIN_DATA 8
#define XCREC_AXILITES_ADDR_CONTROL_REG_CLR_DATA     0x78
#define XCREC_AXILITES_BITS_CONTROL_REG_CLR_DATA     1
#define XCREC_AXILITES_ADDR_CONTROL_REG_INIT_V_DATA  0x80
#define XCREC_AXILITES_BITS_CONTROL_REG_INIT_V_DATA  28

