// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XRESET_AXI_H
#define XRESET_AXI_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xreset_axi_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axi4lites_BaseAddress;
} XReset_axi_Config;
#endif

typedef struct {
    u32 Axi4lites_BaseAddress;
    u32 IsReady;
} XReset_axi;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XReset_axi_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XReset_axi_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XReset_axi_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XReset_axi_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XReset_axi_Initialize(XReset_axi *InstancePtr, u16 DeviceId);
XReset_axi_Config* XReset_axi_LookupConfig(u16 DeviceId);
int XReset_axi_CfgInitialize(XReset_axi *InstancePtr, XReset_axi_Config *ConfigPtr);
#else
int XReset_axi_Initialize(XReset_axi *InstancePtr, const char* InstanceName);
int XReset_axi_Release(XReset_axi *InstancePtr);
#endif


void XReset_axi_SetIn_reset(XReset_axi *InstancePtr, u32 Data);
u32 XReset_axi_GetIn_reset(XReset_axi *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
