// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xtest_direct_dma.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XTest_direct_dma_CfgInitialize(XTest_direct_dma *InstancePtr, XTest_direct_dma_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XTest_direct_dma_Start(XTest_direct_dma *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTest_direct_dma_ReadReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_AP_CTRL) & 0x80;
    XTest_direct_dma_WriteReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XTest_direct_dma_IsDone(XTest_direct_dma *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTest_direct_dma_ReadReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XTest_direct_dma_IsIdle(XTest_direct_dma *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTest_direct_dma_ReadReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XTest_direct_dma_IsReady(XTest_direct_dma *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTest_direct_dma_ReadReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XTest_direct_dma_EnableAutoRestart(XTest_direct_dma *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTest_direct_dma_WriteReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XTest_direct_dma_DisableAutoRestart(XTest_direct_dma *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTest_direct_dma_WriteReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_AP_CTRL, 0);
}

u32 XTest_direct_dma_Get_return(XTest_direct_dma *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTest_direct_dma_ReadReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_AP_RETURN);
    return Data;
}
void XTest_direct_dma_Set_sourceAddress(XTest_direct_dma *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTest_direct_dma_WriteReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_SOURCEADDRESS_DATA, Data);
}

u32 XTest_direct_dma_Get_sourceAddress(XTest_direct_dma *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTest_direct_dma_ReadReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_SOURCEADDRESS_DATA);
    return Data;
}

void XTest_direct_dma_Set_sourceAddress_vld(XTest_direct_dma *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTest_direct_dma_WriteReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_SOURCEADDRESS_CTRL, 1);
}

u32 XTest_direct_dma_Get_sourceAddress_vld(XTest_direct_dma *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTest_direct_dma_ReadReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_SOURCEADDRESS_CTRL);
    return Data & 0x1;
}

void XTest_direct_dma_Set_destinationAddress(XTest_direct_dma *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTest_direct_dma_WriteReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_DESTINATIONADDRESS_DATA, Data);
}

u32 XTest_direct_dma_Get_destinationAddress(XTest_direct_dma *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTest_direct_dma_ReadReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_DESTINATIONADDRESS_DATA);
    return Data;
}

void XTest_direct_dma_Set_destinationAddress_vld(XTest_direct_dma *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTest_direct_dma_WriteReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_DESTINATIONADDRESS_CTRL, 1);
}

u32 XTest_direct_dma_Get_destinationAddress_vld(XTest_direct_dma *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTest_direct_dma_ReadReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_DESTINATIONADDRESS_CTRL);
    return Data & 0x1;
}

void XTest_direct_dma_Set_length_r(XTest_direct_dma *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTest_direct_dma_WriteReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_LENGTH_R_DATA, Data);
}

u32 XTest_direct_dma_Get_length_r(XTest_direct_dma *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTest_direct_dma_ReadReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_LENGTH_R_DATA);
    return Data;
}

void XTest_direct_dma_Set_length_r_vld(XTest_direct_dma *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTest_direct_dma_WriteReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_LENGTH_R_CTRL, 1);
}

u32 XTest_direct_dma_Get_length_r_vld(XTest_direct_dma *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTest_direct_dma_ReadReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_LENGTH_R_CTRL);
    return Data & 0x1;
}

void XTest_direct_dma_InterruptGlobalEnable(XTest_direct_dma *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTest_direct_dma_WriteReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_GIE, 1);
}

void XTest_direct_dma_InterruptGlobalDisable(XTest_direct_dma *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTest_direct_dma_WriteReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_GIE, 0);
}

void XTest_direct_dma_InterruptEnable(XTest_direct_dma *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XTest_direct_dma_ReadReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_IER);
    XTest_direct_dma_WriteReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_IER, Register | Mask);
}

void XTest_direct_dma_InterruptDisable(XTest_direct_dma *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XTest_direct_dma_ReadReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_IER);
    XTest_direct_dma_WriteReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_IER, Register & (~Mask));
}

void XTest_direct_dma_InterruptClear(XTest_direct_dma *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTest_direct_dma_WriteReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_ISR, Mask);
}

u32 XTest_direct_dma_InterruptGetEnabled(XTest_direct_dma *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XTest_direct_dma_ReadReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_IER);
}

u32 XTest_direct_dma_InterruptGetStatus(XTest_direct_dma *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XTest_direct_dma_ReadReg(InstancePtr->Axilites_BaseAddress, XTEST_DIRECT_DMA_AXILITES_ADDR_ISR);
}

