// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XTRIPLE_AES_H
#define XTRIPLE_AES_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xtriple_aes_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XTriple_aes_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XTriple_aes;

typedef struct {
    u32 word_0;
    u32 word_1;
    u32 word_2;
    u32 word_3;
} XTriple_aes_Key_in_v;

typedef struct {
    u32 word_0;
    u32 word_1;
    u32 word_2;
    u32 word_3;
} XTriple_aes_Key_in1_v;

typedef struct {
    u32 word_0;
    u32 word_1;
    u32 word_2;
    u32 word_3;
} XTriple_aes_Key_in2_v;

typedef struct {
    u32 word_0;
    u32 word_1;
    u32 word_2;
    u32 word_3;
} XTriple_aes_Iv_v;

typedef struct {
    u32 word_0;
    u32 word_1;
    u32 word_2;
    u32 word_3;
} XTriple_aes_Iv1_v;

typedef struct {
    u32 word_0;
    u32 word_1;
    u32 word_2;
    u32 word_3;
} XTriple_aes_Iv2_v;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XTriple_aes_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XTriple_aes_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XTriple_aes_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XTriple_aes_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XTriple_aes_Initialize(XTriple_aes *InstancePtr, u16 DeviceId);
XTriple_aes_Config* XTriple_aes_LookupConfig(u16 DeviceId);
int XTriple_aes_CfgInitialize(XTriple_aes *InstancePtr, XTriple_aes_Config *ConfigPtr);
#else
int XTriple_aes_Initialize(XTriple_aes *InstancePtr, const char* InstanceName);
int XTriple_aes_Release(XTriple_aes *InstancePtr);
#endif

void XTriple_aes_Start(XTriple_aes *InstancePtr);
u32 XTriple_aes_IsDone(XTriple_aes *InstancePtr);
u32 XTriple_aes_IsIdle(XTriple_aes *InstancePtr);
u32 XTriple_aes_IsReady(XTriple_aes *InstancePtr);
void XTriple_aes_EnableAutoRestart(XTriple_aes *InstancePtr);
void XTriple_aes_DisableAutoRestart(XTriple_aes *InstancePtr);
u32 XTriple_aes_Get_return(XTriple_aes *InstancePtr);

void XTriple_aes_Set_sourceAddress(XTriple_aes *InstancePtr, u32 Data);
u32 XTriple_aes_Get_sourceAddress(XTriple_aes *InstancePtr);
void XTriple_aes_Set_sourceAddress_vld(XTriple_aes *InstancePtr);
u32 XTriple_aes_Get_sourceAddress_vld(XTriple_aes *InstancePtr);
void XTriple_aes_Set_key_in_V(XTriple_aes *InstancePtr, XTriple_aes_Key_in_v Data);
XTriple_aes_Key_in_v XTriple_aes_Get_key_in_V(XTriple_aes *InstancePtr);
void XTriple_aes_Set_key_in_V_vld(XTriple_aes *InstancePtr);
u32 XTriple_aes_Get_key_in_V_vld(XTriple_aes *InstancePtr);
void XTriple_aes_Set_key_in1_V(XTriple_aes *InstancePtr, XTriple_aes_Key_in1_v Data);
XTriple_aes_Key_in1_v XTriple_aes_Get_key_in1_V(XTriple_aes *InstancePtr);
void XTriple_aes_Set_key_in1_V_vld(XTriple_aes *InstancePtr);
u32 XTriple_aes_Get_key_in1_V_vld(XTriple_aes *InstancePtr);
void XTriple_aes_Set_key_in2_V(XTriple_aes *InstancePtr, XTriple_aes_Key_in2_v Data);
XTriple_aes_Key_in2_v XTriple_aes_Get_key_in2_V(XTriple_aes *InstancePtr);
void XTriple_aes_Set_key_in2_V_vld(XTriple_aes *InstancePtr);
u32 XTriple_aes_Get_key_in2_V_vld(XTriple_aes *InstancePtr);
void XTriple_aes_Set_iv_V(XTriple_aes *InstancePtr, XTriple_aes_Iv_v Data);
XTriple_aes_Iv_v XTriple_aes_Get_iv_V(XTriple_aes *InstancePtr);
void XTriple_aes_Set_iv_V_vld(XTriple_aes *InstancePtr);
u32 XTriple_aes_Get_iv_V_vld(XTriple_aes *InstancePtr);
void XTriple_aes_Set_iv1_V(XTriple_aes *InstancePtr, XTriple_aes_Iv1_v Data);
XTriple_aes_Iv1_v XTriple_aes_Get_iv1_V(XTriple_aes *InstancePtr);
void XTriple_aes_Set_iv1_V_vld(XTriple_aes *InstancePtr);
u32 XTriple_aes_Get_iv1_V_vld(XTriple_aes *InstancePtr);
void XTriple_aes_Set_iv2_V(XTriple_aes *InstancePtr, XTriple_aes_Iv2_v Data);
XTriple_aes_Iv2_v XTriple_aes_Get_iv2_V(XTriple_aes *InstancePtr);
void XTriple_aes_Set_iv2_V_vld(XTriple_aes *InstancePtr);
u32 XTriple_aes_Get_iv2_V_vld(XTriple_aes *InstancePtr);
void XTriple_aes_Set_destinationAddress(XTriple_aes *InstancePtr, u32 Data);
u32 XTriple_aes_Get_destinationAddress(XTriple_aes *InstancePtr);
void XTriple_aes_Set_destinationAddress_vld(XTriple_aes *InstancePtr);
u32 XTriple_aes_Get_destinationAddress_vld(XTriple_aes *InstancePtr);
void XTriple_aes_Set_numBytes(XTriple_aes *InstancePtr, u32 Data);
u32 XTriple_aes_Get_numBytes(XTriple_aes *InstancePtr);
void XTriple_aes_Set_numBytes_vld(XTriple_aes *InstancePtr);
u32 XTriple_aes_Get_numBytes_vld(XTriple_aes *InstancePtr);
void XTriple_aes_Set_mode(XTriple_aes *InstancePtr, u32 Data);
u32 XTriple_aes_Get_mode(XTriple_aes *InstancePtr);
void XTriple_aes_Set_mode_vld(XTriple_aes *InstancePtr);
u32 XTriple_aes_Get_mode_vld(XTriple_aes *InstancePtr);

void XTriple_aes_InterruptGlobalEnable(XTriple_aes *InstancePtr);
void XTriple_aes_InterruptGlobalDisable(XTriple_aes *InstancePtr);
void XTriple_aes_InterruptEnable(XTriple_aes *InstancePtr, u32 Mask);
void XTriple_aes_InterruptDisable(XTriple_aes *InstancePtr, u32 Mask);
void XTriple_aes_InterruptClear(XTriple_aes *InstancePtr, u32 Mask);
u32 XTriple_aes_InterruptGetEnabled(XTriple_aes *InstancePtr);
u32 XTriple_aes_InterruptGetStatus(XTriple_aes *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
