// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of ap_return
//        bit 0  - ap_return[0] (Read)
//        others - reserved
// 0x18 : Data signal of sourceAddress
//        bit 31~0 - sourceAddress[31:0] (Read/Write)
// 0x1c : Control signal of sourceAddress
//        bit 0  - sourceAddress_ap_vld (Read/Write/SC)
//        others - reserved
// 0x20 : Data signal of key_in_V
//        bit 31~0 - key_in_V[31:0] (Read/Write)
// 0x24 : Data signal of key_in_V
//        bit 31~0 - key_in_V[63:32] (Read/Write)
// 0x28 : Data signal of key_in_V
//        bit 31~0 - key_in_V[95:64] (Read/Write)
// 0x2c : Data signal of key_in_V
//        bit 31~0 - key_in_V[127:96] (Read/Write)
// 0x30 : Control signal of key_in_V
//        bit 0  - key_in_V_ap_vld (Read/Write/SC)
//        others - reserved
// 0x34 : Data signal of key_in1_V
//        bit 31~0 - key_in1_V[31:0] (Read/Write)
// 0x38 : Data signal of key_in1_V
//        bit 31~0 - key_in1_V[63:32] (Read/Write)
// 0x3c : Data signal of key_in1_V
//        bit 31~0 - key_in1_V[95:64] (Read/Write)
// 0x40 : Data signal of key_in1_V
//        bit 31~0 - key_in1_V[127:96] (Read/Write)
// 0x44 : Control signal of key_in1_V
//        bit 0  - key_in1_V_ap_vld (Read/Write/SC)
//        others - reserved
// 0x48 : Data signal of key_in2_V
//        bit 31~0 - key_in2_V[31:0] (Read/Write)
// 0x4c : Data signal of key_in2_V
//        bit 31~0 - key_in2_V[63:32] (Read/Write)
// 0x50 : Data signal of key_in2_V
//        bit 31~0 - key_in2_V[95:64] (Read/Write)
// 0x54 : Data signal of key_in2_V
//        bit 31~0 - key_in2_V[127:96] (Read/Write)
// 0x58 : Control signal of key_in2_V
//        bit 0  - key_in2_V_ap_vld (Read/Write/SC)
//        others - reserved
// 0x5c : Data signal of iv_V
//        bit 31~0 - iv_V[31:0] (Read/Write)
// 0x60 : Data signal of iv_V
//        bit 31~0 - iv_V[63:32] (Read/Write)
// 0x64 : Data signal of iv_V
//        bit 31~0 - iv_V[95:64] (Read/Write)
// 0x68 : Data signal of iv_V
//        bit 31~0 - iv_V[127:96] (Read/Write)
// 0x6c : Control signal of iv_V
//        bit 0  - iv_V_ap_vld (Read/Write/SC)
//        others - reserved
// 0x70 : Data signal of iv1_V
//        bit 31~0 - iv1_V[31:0] (Read/Write)
// 0x74 : Data signal of iv1_V
//        bit 31~0 - iv1_V[63:32] (Read/Write)
// 0x78 : Data signal of iv1_V
//        bit 31~0 - iv1_V[95:64] (Read/Write)
// 0x7c : Data signal of iv1_V
//        bit 31~0 - iv1_V[127:96] (Read/Write)
// 0x80 : Control signal of iv1_V
//        bit 0  - iv1_V_ap_vld (Read/Write/SC)
//        others - reserved
// 0x84 : Data signal of iv2_V
//        bit 31~0 - iv2_V[31:0] (Read/Write)
// 0x88 : Data signal of iv2_V
//        bit 31~0 - iv2_V[63:32] (Read/Write)
// 0x8c : Data signal of iv2_V
//        bit 31~0 - iv2_V[95:64] (Read/Write)
// 0x90 : Data signal of iv2_V
//        bit 31~0 - iv2_V[127:96] (Read/Write)
// 0x94 : Control signal of iv2_V
//        bit 0  - iv2_V_ap_vld (Read/Write/SC)
//        others - reserved
// 0x98 : Data signal of destinationAddress
//        bit 31~0 - destinationAddress[31:0] (Read/Write)
// 0x9c : Control signal of destinationAddress
//        bit 0  - destinationAddress_ap_vld (Read/Write/SC)
//        others - reserved
// 0xa0 : Data signal of numBytes
//        bit 31~0 - numBytes[31:0] (Read/Write)
// 0xa4 : Control signal of numBytes
//        bit 0  - numBytes_ap_vld (Read/Write/SC)
//        others - reserved
// 0xa8 : Data signal of mode
//        bit 31~0 - mode[31:0] (Read/Write)
// 0xac : Control signal of mode
//        bit 0  - mode_ap_vld (Read/Write/SC)
//        others - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XTRIPLE_AES_AXILITES_ADDR_AP_CTRL                 0x00
#define XTRIPLE_AES_AXILITES_ADDR_GIE                     0x04
#define XTRIPLE_AES_AXILITES_ADDR_IER                     0x08
#define XTRIPLE_AES_AXILITES_ADDR_ISR                     0x0c
#define XTRIPLE_AES_AXILITES_ADDR_AP_RETURN               0x10
#define XTRIPLE_AES_AXILITES_BITS_AP_RETURN               1
#define XTRIPLE_AES_AXILITES_ADDR_SOURCEADDRESS_DATA      0x18
#define XTRIPLE_AES_AXILITES_BITS_SOURCEADDRESS_DATA      32
#define XTRIPLE_AES_AXILITES_ADDR_SOURCEADDRESS_CTRL      0x1c
#define XTRIPLE_AES_AXILITES_ADDR_KEY_IN_V_DATA           0x20
#define XTRIPLE_AES_AXILITES_BITS_KEY_IN_V_DATA           128
#define XTRIPLE_AES_AXILITES_ADDR_KEY_IN_V_CTRL           0x30
#define XTRIPLE_AES_AXILITES_ADDR_KEY_IN1_V_DATA          0x34
#define XTRIPLE_AES_AXILITES_BITS_KEY_IN1_V_DATA          128
#define XTRIPLE_AES_AXILITES_ADDR_KEY_IN1_V_CTRL          0x44
#define XTRIPLE_AES_AXILITES_ADDR_KEY_IN2_V_DATA          0x48
#define XTRIPLE_AES_AXILITES_BITS_KEY_IN2_V_DATA          128
#define XTRIPLE_AES_AXILITES_ADDR_KEY_IN2_V_CTRL          0x58
#define XTRIPLE_AES_AXILITES_ADDR_IV_V_DATA               0x5c
#define XTRIPLE_AES_AXILITES_BITS_IV_V_DATA               128
#define XTRIPLE_AES_AXILITES_ADDR_IV_V_CTRL               0x6c
#define XTRIPLE_AES_AXILITES_ADDR_IV1_V_DATA              0x70
#define XTRIPLE_AES_AXILITES_BITS_IV1_V_DATA              128
#define XTRIPLE_AES_AXILITES_ADDR_IV1_V_CTRL              0x80
#define XTRIPLE_AES_AXILITES_ADDR_IV2_V_DATA              0x84
#define XTRIPLE_AES_AXILITES_BITS_IV2_V_DATA              128
#define XTRIPLE_AES_AXILITES_ADDR_IV2_V_CTRL              0x94
#define XTRIPLE_AES_AXILITES_ADDR_DESTINATIONADDRESS_DATA 0x98
#define XTRIPLE_AES_AXILITES_BITS_DESTINATIONADDRESS_DATA 32
#define XTRIPLE_AES_AXILITES_ADDR_DESTINATIONADDRESS_CTRL 0x9c
#define XTRIPLE_AES_AXILITES_ADDR_NUMBYTES_DATA           0xa0
#define XTRIPLE_AES_AXILITES_BITS_NUMBYTES_DATA           32
#define XTRIPLE_AES_AXILITES_ADDR_NUMBYTES_CTRL           0xa4
#define XTRIPLE_AES_AXILITES_ADDR_MODE_DATA               0xa8
#define XTRIPLE_AES_AXILITES_BITS_MODE_DATA               32
#define XTRIPLE_AES_AXILITES_ADDR_MODE_CTRL               0xac

