// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xtriple_aes.h"

extern XTriple_aes_Config XTriple_aes_ConfigTable[];

XTriple_aes_Config *XTriple_aes_LookupConfig(u16 DeviceId) {
	XTriple_aes_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XTRIPLE_AES_NUM_INSTANCES; Index++) {
		if (XTriple_aes_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XTriple_aes_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XTriple_aes_Initialize(XTriple_aes *InstancePtr, u16 DeviceId) {
	XTriple_aes_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XTriple_aes_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XTriple_aes_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

