// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xcrec.h"

extern XCrec_Config XCrec_ConfigTable[];

XCrec_Config *XCrec_LookupConfig(u16 DeviceId) {
	XCrec_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XCREC_NUM_INSTANCES; Index++) {
		if (XCrec_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XCrec_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XCrec_Initialize(XCrec *InstancePtr, u16 DeviceId) {
	XCrec_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XCrec_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XCrec_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

