// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xqam_runner.h"

extern XQam_runner_Config XQam_runner_ConfigTable[];

XQam_runner_Config *XQam_runner_LookupConfig(u16 DeviceId) {
	XQam_runner_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XQAM_RUNNER_NUM_INSTANCES; Index++) {
		if (XQam_runner_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XQam_runner_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XQam_runner_Initialize(XQam_runner *InstancePtr, u16 DeviceId) {
	XQam_runner_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XQam_runner_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XQam_runner_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

