// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of ap_return
//        bit 0  - ap_return[0] (Read)
//        others - reserved
// 0x18 : Data signal of input_d_i
//        bit 31~0 - input_d_i[31:0] (Read/Write)
// 0x1c : Control signal of input_d_i
//        bit 0  - input_d_i_ap_vld (Read/Write/SC)
//        others - reserved
// 0x20 : Data signal of input_d_q
//        bit 31~0 - input_d_q[31:0] (Read/Write)
// 0x24 : Control signal of input_d_q
//        bit 0  - input_d_q_ap_vld (Read/Write/SC)
//        others - reserved
// 0x28 : Data signal of output_d_i
//        bit 31~0 - output_d_i[31:0] (Read)
// 0x2c : reserved
// 0x30 : Data signal of output_d_q
//        bit 31~0 - output_d_q[31:0] (Read)
// 0x34 : reserved
// 0x38 : Data signal of input_ph_i
//        bit 31~0 - input_ph_i[31:0] (Read/Write)
// 0x3c : Control signal of input_ph_i
//        bit 0  - input_ph_i_ap_vld (Read/Write/SC)
//        others - reserved
// 0x40 : Data signal of input_ph_q
//        bit 31~0 - input_ph_q[31:0] (Read/Write)
// 0x44 : Control signal of input_ph_q
//        bit 0  - input_ph_q_ap_vld (Read/Write/SC)
//        others - reserved
// 0x48 : Data signal of output_ph_i
//        bit 31~0 - output_ph_i[31:0] (Read)
// 0x4c : Control signal of output_ph_i
//        bit 0  - output_ph_i_ap_vld (Read/COR)
//        others - reserved
// 0x50 : Data signal of output_ph_q
//        bit 31~0 - output_ph_q[31:0] (Read)
// 0x54 : Control signal of output_ph_q
//        bit 0  - output_ph_q_ap_vld (Read/COR)
//        others - reserved
// 0x58 : Data signal of loop_out
//        bit 31~0 - loop_out[31:0] (Read)
// 0x5c : Control signal of loop_out
//        bit 0  - loop_out_ap_vld (Read/COR)
//        others - reserved
// 0x60 : Data signal of control_in_qam
//        bit 31~0 - control_in_qam[31:0] (Read/Write)
// 0x64 : Control signal of control_in_qam
//        bit 0  - control_in_qam_ap_vld (Read/Write/SC)
//        others - reserved
// 0x68 : Data signal of control_in_lf_p
//        bit 7~0 - control_in_lf_p[7:0] (Read/Write)
//        others  - reserved
// 0x6c : Control signal of control_in_lf_p
//        bit 0  - control_in_lf_p_ap_vld (Read/Write/SC)
//        others - reserved
// 0x70 : Data signal of control_in_lf_i
//        bit 7~0 - control_in_lf_i[7:0] (Read/Write)
//        others  - reserved
// 0x74 : Control signal of control_in_lf_i
//        bit 0  - control_in_lf_i_ap_vld (Read/Write/SC)
//        others - reserved
// 0x78 : Data signal of control_in_lf_out_gain
//        bit 7~0 - control_in_lf_out_gain[7:0] (Read/Write)
//        others  - reserved
// 0x7c : Control signal of control_in_lf_out_gain
//        bit 0  - control_in_lf_out_gain_ap_vld (Read/Write/SC)
//        others - reserved
// 0x80 : Data signal of control_in_reg_clr
//        bit 0  - control_in_reg_clr[0] (Read/Write)
//        others - reserved
// 0x84 : Control signal of control_in_reg_clr
//        bit 0  - control_in_reg_clr_ap_vld (Read/Write/SC)
//        others - reserved
// 0x88 : Data signal of control_in_reg_init
//        bit 31~0 - control_in_reg_init[31:0] (Read/Write)
// 0x8c : Control signal of control_in_reg_init
//        bit 0  - control_in_reg_init_ap_vld (Read/Write/SC)
//        others - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XQAM_RUNNER_AXILITES_ADDR_AP_CTRL                     0x00
#define XQAM_RUNNER_AXILITES_ADDR_GIE                         0x04
#define XQAM_RUNNER_AXILITES_ADDR_IER                         0x08
#define XQAM_RUNNER_AXILITES_ADDR_ISR                         0x0c
#define XQAM_RUNNER_AXILITES_ADDR_AP_RETURN                   0x10
#define XQAM_RUNNER_AXILITES_BITS_AP_RETURN                   1
#define XQAM_RUNNER_AXILITES_ADDR_INPUT_D_I_DATA              0x18
#define XQAM_RUNNER_AXILITES_BITS_INPUT_D_I_DATA              32
#define XQAM_RUNNER_AXILITES_ADDR_INPUT_D_I_CTRL              0x1c
#define XQAM_RUNNER_AXILITES_ADDR_INPUT_D_Q_DATA              0x20
#define XQAM_RUNNER_AXILITES_BITS_INPUT_D_Q_DATA              32
#define XQAM_RUNNER_AXILITES_ADDR_INPUT_D_Q_CTRL              0x24
#define XQAM_RUNNER_AXILITES_ADDR_OUTPUT_D_I_DATA             0x28
#define XQAM_RUNNER_AXILITES_BITS_OUTPUT_D_I_DATA             32
#define XQAM_RUNNER_AXILITES_ADDR_OUTPUT_D_Q_DATA             0x30
#define XQAM_RUNNER_AXILITES_BITS_OUTPUT_D_Q_DATA             32
#define XQAM_RUNNER_AXILITES_ADDR_INPUT_PH_I_DATA             0x38
#define XQAM_RUNNER_AXILITES_BITS_INPUT_PH_I_DATA             32
#define XQAM_RUNNER_AXILITES_ADDR_INPUT_PH_I_CTRL             0x3c
#define XQAM_RUNNER_AXILITES_ADDR_INPUT_PH_Q_DATA             0x40
#define XQAM_RUNNER_AXILITES_BITS_INPUT_PH_Q_DATA             32
#define XQAM_RUNNER_AXILITES_ADDR_INPUT_PH_Q_CTRL             0x44
#define XQAM_RUNNER_AXILITES_ADDR_OUTPUT_PH_I_DATA            0x48
#define XQAM_RUNNER_AXILITES_BITS_OUTPUT_PH_I_DATA            32
#define XQAM_RUNNER_AXILITES_ADDR_OUTPUT_PH_I_CTRL            0x4c
#define XQAM_RUNNER_AXILITES_ADDR_OUTPUT_PH_Q_DATA            0x50
#define XQAM_RUNNER_AXILITES_BITS_OUTPUT_PH_Q_DATA            32
#define XQAM_RUNNER_AXILITES_ADDR_OUTPUT_PH_Q_CTRL            0x54
#define XQAM_RUNNER_AXILITES_ADDR_LOOP_OUT_DATA               0x58
#define XQAM_RUNNER_AXILITES_BITS_LOOP_OUT_DATA               32
#define XQAM_RUNNER_AXILITES_ADDR_LOOP_OUT_CTRL               0x5c
#define XQAM_RUNNER_AXILITES_ADDR_CONTROL_IN_QAM_DATA         0x60
#define XQAM_RUNNER_AXILITES_BITS_CONTROL_IN_QAM_DATA         32
#define XQAM_RUNNER_AXILITES_ADDR_CONTROL_IN_QAM_CTRL         0x64
#define XQAM_RUNNER_AXILITES_ADDR_CONTROL_IN_LF_P_DATA        0x68
#define XQAM_RUNNER_AXILITES_BITS_CONTROL_IN_LF_P_DATA        8
#define XQAM_RUNNER_AXILITES_ADDR_CONTROL_IN_LF_P_CTRL        0x6c
#define XQAM_RUNNER_AXILITES_ADDR_CONTROL_IN_LF_I_DATA        0x70
#define XQAM_RUNNER_AXILITES_BITS_CONTROL_IN_LF_I_DATA        8
#define XQAM_RUNNER_AXILITES_ADDR_CONTROL_IN_LF_I_CTRL        0x74
#define XQAM_RUNNER_AXILITES_ADDR_CONTROL_IN_LF_OUT_GAIN_DATA 0x78
#define XQAM_RUNNER_AXILITES_BITS_CONTROL_IN_LF_OUT_GAIN_DATA 8
#define XQAM_RUNNER_AXILITES_ADDR_CONTROL_IN_LF_OUT_GAIN_CTRL 0x7c
#define XQAM_RUNNER_AXILITES_ADDR_CONTROL_IN_REG_CLR_DATA     0x80
#define XQAM_RUNNER_AXILITES_BITS_CONTROL_IN_REG_CLR_DATA     1
#define XQAM_RUNNER_AXILITES_ADDR_CONTROL_IN_REG_CLR_CTRL     0x84
#define XQAM_RUNNER_AXILITES_ADDR_CONTROL_IN_REG_INIT_DATA    0x88
#define XQAM_RUNNER_AXILITES_BITS_CONTROL_IN_REG_INIT_DATA    32
#define XQAM_RUNNER_AXILITES_ADDR_CONTROL_IN_REG_INIT_CTRL    0x8c

